# basic options
title: Miguel Gonzalez-Bolívar
author: Miguel Gonzalez-Bolivar
email: miguel-angel.gonzalez-boliv@mq.edu.au
description: PhD student at Macquarie University 
github_username:  miguelglezb

fonts:
  heading: "Fira Mono"

# Build settings
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one